<a href="https://colab.research.google.com/github/HarryAI-6748/ml-project/blob/main/Copy_of_Question1_Pandas_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Writing a Dictionary corresponding to the table in the question

In [ ]:
student = {
    "StudentID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Ethan"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [88, 75, 92, 65, 78],
    "Grade": ["A", "B", "A", "C", "B"]
}

Importing pandas as pd and converting the dictionary into a data frame. Then adding that data frame into a file named student.csv

In [ ]:
import pandas as pd
st_df = pd.DataFrame(student)
st_df.to_csv('student.csv', index = False)

Reading the csv file using read_csv method

In [ ]:
pd.read_csv('student.csv')

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B

Printing the first 3 rows of the data frame

In [ ]:
st_df.head(3)

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A

Using describe() method to get the numerical statistical data

In [ ]:
st_df.describe()

        StudentID        Age      Marks
count    5.000000   5.000000   5.000000
mean   103.000000  20.400000  79.600000
std      1.581139   1.140175  10.737784
min    101.000000  19.000000  65.000000
25%    102.000000  20.000000  75.000000
50%    103.000000  20.000000  78.000000
75%    104.000000  21.000000  88.000000
max    105.000000  22.000000  92.000000

As is makes sense only for the age and marks column to have a statistical data, describe() method is applied on Age column

In [ ]:
age_des = st_df['Age'].describe()
age_des

count     5.000000
mean     20.400000
std       1.140175
min      19.000000
25%      20.000000
50%      20.000000
75%      21.000000
max      22.000000
Name: Age, dtype: float64

As is makes sense only for the age and marks column to have a statistical data, describe() method is applied on Marks column

In [ ]:
marks_des = st_df['Marks'].describe()
marks_des

count     5.000000
mean     79.600000
std      10.737784
min      65.000000
25%      75.000000
50%      78.000000
75%      88.000000
max      92.000000
Name: Marks, dtype: float64

Printing the shape of the data showing rows:columns in the data frame

In [ ]:
st_df.shape

(5, 5)

Printing the data types of individual column

In [ ]:
st_df.dtypes

StudentID     int64
Name         object
Age           int64
Marks         int64
Grade        object
dtype: object

Getting the general details of the data frame

In [ ]:
st_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  5 non-null      int64
 1   Name       5 non-null      object
 2   Age        5 non-null      int64
 3   Marks      5 non-null      int64
 4   Grade      5 non-null      object
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes