<a href="https://colab.research.google.com/github/HarryAI-6748/ml-project/blob/main/Data_Merging_and_Lookup_Operations_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None, 'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}

In [48]:
enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python', 'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-10', '2024-02-15', '2024-03-01']
}

In [49]:
scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}

=== TASK 1: Data Preparation ===

Generating the Data Frames using the above 3 dictionaries

In [50]:
import pandas as pd
import numpy as np

In [51]:
stn_df = pd.DataFrame(students_data)
enll_df = pd.DataFrame(enrollments_data)
scr_df = pd.DataFrame(scores_data)

Printing all the newly generated Data Frames

In [52]:
stn_df

   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com       None
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi

In [7]:
stn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  7 non-null      int64
 1   name        6 non-null      object
 2   email       6 non-null      object
 3   city        6 non-null      object
dtypes: int64(1), object(3)
memory usage: 356.0+ bytes

In [53]:
enll_df

   student_id       course_name enrollment_date
0         101            Python      2024-01-15
1         102      Data Science      2024-01-20
2         103            Python      2024-02-01
3         105  Machine Learning      2024-02-10
4         108                AI      2024-02-15
5         109            Python      2024-03-01

In [54]:
enll_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   student_id       6 non-null      int64
 1   course_name      6 non-null      object
 2   enrollment_date  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [9]:
scr_df

   student_id  exam_score
0         101          85
1         102          92
2         104          78
3         105          88
4         106          95

In [55]:
scr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  5 non-null      int64
 1   exam_score  5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes

For students DataFrame i.e (stn_df)
Displaying null value count and percentage for each column

In [56]:
print("The null value count for each column is:")
stn_df.isnull().sum()

The null value count for each column is:

student_id    0
name          1
email         1
city          1
dtype: int64

In [57]:
print("The percentage of null values in each column is:")
stn_df.isnull().sum() / len(stn_df) * 100

The percentage of null values in each column is:

student_id     0.000000
name          14.285714
email         14.285714
city          14.285714
dtype: float64

For stn_df filling missing 'city' values with 'Unknown'

In [58]:
stn_df['city'] = stn_df['city'].fillna('Unknown')
stn_df['city']

0       Mumbai
1        Delhi
2    Bangalore
3       Mumbai
4      Unknown
5      Chennai
6        Delhi
Name: city, dtype: object

Dropping rows where 'name' is missing. It means the name value in that row will be null.

In [59]:
stn_df = stn_df.dropna(subset = ['name'])
stn_df.dropna(subset = ['name'])

   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi

Displaying the cleaned students DataFrame

In [60]:
stn_df

   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi

=== TASK 2: Join Operations ===

Carrying out a Inner Join: Merging students and enrollments on student_id

In [61]:
pd.merge(stn_df, enll_df)# It performs a inner join as default

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10

How many students appear in the result?

Only 03 students appear in the merged dataframe when inner join operation is performed on student and enrollment dataframes.

Which students from the students table are excluded and why?

Student ID (103, 104, 106, 107, 108, 109) were excluded because these student id were either not commom in both dataframes or they had a null value in that row corresponding to that student ID.

Performing Left Join: Merging students and enrollments on student_id

In [62]:
pd.merge(stn_df, enll_df, how = 'left')# It performs a left join as default

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,104,David,None,Mumbai,NaN,NaN
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,NaN,NaN
5,107,Grace,grace@email.com,Delhi,NaN,NaN

In [63]:
pd.merge(stn_df, enll_df, how = 'left').shape[0]# Number of rows after perfoming left join

6

The following students have null values in their course_name beacause student ID 104, 106 and 107 course name data don't exists in student dataframe. As we have performed a left join, all the student ID's from left dataframe i.e Stn_df are included in the output evenif there is a null value present while merging them.

In [64]:
(pd.merge(stn_df, enll_df, how = 'left'))[(pd.merge(stn_df, enll_df, how = 'left'))['course_name'].isnull()]

   student_id   name            email     city course_name enrollment_date
2         104  David             None   Mumbai         NaN             NaN
4         106  Frank  frank@email.com  Chennai         NaN             NaN
5         107  Grace  grace@email.com    Delhi         NaN             NaN

Performing Right Join: Merging students and enrollments on student_id

In [65]:
pd.merge(stn_df, enll_df, how = 'right')

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,108,NaN,NaN,NaN,AI,2024-02-15
5,109,NaN,NaN,NaN,Python,2024-03-01

In [66]:
pd.merge(stn_df, enll_df, how = 'right').shape[0]# Number of rows after performing right join operation

6

The following student ID's are without student names

In [67]:
pd.merge(stn_df, enll_df, how = 'right')[(pd.merge(stn_df, enll_df, how = 'right'))['name'].isnull()]

   student_id name email city course_name enrollment_date
2         103  NaN   NaN  NaN      Python      2024-02-01
4         108  NaN   NaN  NaN          AI      2024-02-15
5         109  NaN   NaN  NaN      Python      2024-03-01

Performing Full outer Join: Merging students and enrollments on student_id

In [68]:
pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id')

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,104,David,None,Mumbai,NaN,NaN
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
5,106,Frank,frank@email.com,Chennai,NaN,NaN
6,107,Grace,grace@email.com,Delhi,NaN,NaN
7,108,NaN,NaN,NaN,AI,2024-02-15
8,109,NaN,NaN,NaN,Python,2024-03-01

In [69]:
pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id').shape[0]# Number of rows after performing outer join operation

9

Displaying rows where either student name is null OR course_name is null

In [70]:
pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id')[(pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id'))['name'].isnull()]

   student_id name email city course_name enrollment_date
2         103  NaN   NaN  NaN      Python      2024-02-01
7         108  NaN   NaN  NaN          AI      2024-02-15
8         109  NaN   NaN  NaN      Python      2024-03-01

In [72]:
pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id')[(pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id'))['course_name'].isnull()]

   student_id   name            email     city course_name enrollment_date
3         104  David             None   Mumbai         NaN             NaN
5         106  Frank  frank@email.com  Chennai         NaN             NaN
6         107  Grace  grace@email.com    Delhi         NaN             NaN

In [90]:
x = (pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id'))['name'].isnull()
print(f"The number of null values in 'name' column is: {x.sum()}", "\n")
print(x, "\n")
#
y = (pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id'))['course_name'].isnull()
print(f"The number of null values in 'course_name' column is: {y.sum()}", "\n")
print(y, "\n")
#
print(f"Combining the result of x and y:", "\n")
#
z = (x + y).sum()
print(f"The number of rows which have null value in both the data frames is: {z}", "\n")
#
(pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id'))[(x + y)]

The number of null values in 'name' column is: 3

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
8     True
Name: name, dtype: bool

The number of null values in 'course_name' column is: 3

0    False
1    False
2    False
3     True
4    False
5     True
6     True
7    False
8    False
Name: course_name, dtype: bool

Combining the result of x and y:

The number of rows which have null value in both the data frames is: 6

   student_id   name            email     city course_name enrollment_date
2         103    NaN              NaN      NaN      Python      2024-02-01
3         104  David             None   Mumbai         NaN             NaN
5         106  Frank  frank@email.com  Chennai         NaN             NaN
6         107  Grace  grace@email.com    Delhi         NaN             NaN
7         108    NaN              NaN      NaN          AI      2024-02-15
8         109    NaN              NaN      NaN      Python      2024-03-01

Adding indicator=True parameter to the outer join and showing the distribution of merge sources '_merge column'

In [91]:
pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id', indicator = True)

,student_id,name,email,city,course_name,enrollment_date,_merge
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15,both
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20,both
2,103,NaN,NaN,NaN,Python,2024-02-01,right_only
3,104,David,None,Mumbai,NaN,NaN,left_only
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10,both
5,106,Frank,frank@email.com,Chennai,NaN,NaN,left_only
6,107,Grace,grace@email.com,Delhi,NaN,NaN,left_only
7,108,NaN,NaN,NaN,AI,2024-02-15,right_only
8,109,NaN,NaN,NaN,Python,2024-03-01,right_only

Showing the _merge column

In [95]:
(pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id', indicator = True))['_merge']

0          both
1          both
2    right_only
3     left_only
4          both
5     left_only
6     left_only
7    right_only
8    right_only
Name: _merge, dtype: category
Categories (3, object): ['left_only', 'right_only', 'both']

Showing the counts of _merge column

In [96]:
(pd.merge(stn_df, enll_df, how = 'outer', on = 'student_id', indicator = True))['_merge'].value_counts()

_merge
left_only     3
right_only    3
both          3
Name: count, dtype: int64

=== TASK 3: Lookup and Automation ===

Lookup Operation:

Creating a dictionary mapping student_id to exam_score from the scores DataFrame

In [99]:
stn_scr = dict(zip(stn_df['student_id'], scr_df['exam_score']))
print(f"The lookup dictionary is: {stn_scr}")

The lookup dictionary is: {101: 85, 102: 92, 104: 78, 105: 88, 106: 95}

Using the .map() function to add exam scores to the students DataFrame

In [102]:
stn_df['exam_score'] = stn_df['student_id'].map(stn_scr)
stn_df

/tmp/ipykernel_1887/2096983310.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stn_df['exam_score'] = stn_df['student_id'].map(stn_scr)

   student_id   name            email     city  exam_score
0         101  Alice  alice@email.com   Mumbai        85.0
1         102    Bob    bob@email.com    Delhi        92.0
3         104  David             None   Mumbai        78.0
4         105   Emma   emma@email.com  Unknown        88.0
5         106  Frank  frank@email.com  Chennai        95.0
6         107  Grace  grace@email.com    Delhi         NaN

Displaying students with their scores (showing NaN for students without scores)

In [103]:
stn_df['exam_score']

0    85.0
1    92.0
3    78.0
4    88.0
5    95.0
6     NaN
Name: exam_score, dtype: float64

Performance Comparison

Implementing the same score addition using pd.merge() with a left join

In [108]:
pd.merge(stn_df, scr_df, how = 'left', on = 'student_id').drop(columns = ['exam_score_y'])

   student_id   name            email     city  exam_score_x
0         101  Alice  alice@email.com   Mumbai          85.0
1         102    Bob    bob@email.com    Delhi          92.0
2         104  David             None   Mumbai          78.0
3         105   Emma   emma@email.com  Unknown          88.0
4         106  Frank  frank@email.com  Chennai          95.0
5         107  Grace  grace@email.com    Delhi           NaN

Why lookup (map) is more efficient than merge for this scenario?

Lookup is more efficient because the merge operations applied here is executed to entire arrays of data at once, rather than element by element. So it reduces the time and optimises memory required to complete this task.

Simple Automation: Defining the funtion

In [124]:
def auto_merge(df1, df2, join_type, key_column):
  mrg_dict = pd.merge(df1, df2, how = join_type, on = key_column)
  formatted_output = {
      'result_df': mrg_dict,
      'row_count': mrg_dict.shape[0],
      'join_type': join_type,
  }
  fm_op = print("Rows in Result:", mrg_dict.shape[0], "\n", "Join type:", join_type, "\n", f"Result preview:\n {mrg_dict}")
  return fm_op

Test 1

In [125]:
r = auto_merge(stn_df, enll_df, 'left', 'student_id')
r

Rows in Result: 6
 Join type: left
 Result preview:
    student_id   name            email     city  exam_score       course_name  \
0         101  Alice  alice@email.com   Mumbai        85.0            Python
1         102    Bob    bob@email.com    Delhi        92.0      Data Science
2         104  David             None   Mumbai        78.0               NaN
3         105   Emma   emma@email.com  Unknown        88.0  Machine Learning
4         106  Frank  frank@email.com  Chennai        95.0               NaN
5         107  Grace  grace@email.com    Delhi         NaN               NaN

  enrollment_date
0      2024-01-15
1      2024-01-20
2             NaN
3      2024-02-10
4             NaN
5             NaN

Test 2

In [127]:
s = auto_merge(stn_df, scr_df, 'right', 'student_id')

Rows in Result: 5
 Join type: right
 Result preview:
    student_id   name            email     city  exam_score_x  exam_score_y
0         101  Alice  alice@email.com   Mumbai          85.0            85
1         102    Bob    bob@email.com    Delhi          92.0            92
2         104  David             None   Mumbai          78.0            78
3         105   Emma   emma@email.com  Unknown          88.0            88
4         106  Frank  frank@email.com  Chennai          95.0            95