<a href="https://colab.research.google.com/github/HarryAI-6748/ml-project/blob/main/Evaluation_Module_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Python function called `word_frequency` that:
1. Takes a filename (string) as its only parameter
2. Opens and reads the file using a context manager (`with` statement)
3. Counts how many times each word appears in the file (case-insensitive)
4. Returns a dictionary where keys are words (lowercase) and values are their counts

Example: If the file contains: 'Hello world hello Python world world'
Expected output: {'hello': 2, 'world': 3, 'python': 1}

In [38]:
def word_frequency(filename):
  with open(filename, 'r') as file:
    text = file.read()
    text = text.lower()
    words = text.split()
    #print(words)
    word_count = {}
    for word in words:
      word_count[word] = 0
      #print(word_count)
    for word in words:
      if word in word_count:
        word_count[word] += 1
    #print(word_count)
    return word_count

In [11]:
with open('filename.txt', 'w') as file:
  file.write('Hello world hello Python world world')

In [40]:
word_frequency('filename.txt')

{'hello': 2, 'world': 3, 'python': 1}

In [39]:
x = word_frequency('filename.txt')
x

{'hello': 2, 'world': 3, 'python': 1}

Write code to:
1. Print the count AND percentage of missing values in the 'score' column
2. Fill missing scores with the SUBJECT-GROUP median (missing Maths scores get the Maths median; Science gets Science median)
3. Compute and print the mean score per subject using groupby
4. Convert the 'grade' column to Pandas category dtype

Use Pandas vectorized operations — no manual loops for steps 2-4.

In [41]:

import pandas as pd, numpy as np
data = {
    'student_id': [1,2,3,4,5,6,7,8,9,10],
    'subject':    ['Maths','Science','Maths','Science','Maths',
                   'Science','Maths','Science','Maths','Science'],
    'score':      [85, np.nan, 92, 78, np.nan, 88, 76, np.nan, 91, 84],
    'grade':      ['A','B','A','B','A','A','B','B','A','B']
}
df = pd.DataFrame(data)

In [58]:
df

   student_id  subject  score grade
0           1    Maths   85.0     A
1           2  Science    NaN     B
2           3    Maths   92.0     A
3           4  Science   78.0     B
4           5    Maths    NaN     A
5           6  Science   88.0     A
6           7    Maths   76.0     B
7           8  Science    NaN     B
8           9    Maths   91.0     A
9          10  Science   84.0     B

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  10 non-null     int64
 1   subject     10 non-null     object
 2   score       7 non-null      float64
 3   grade       10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [68]:
df.describe()

       student_id      score
count    10.00000   7.000000
mean      5.50000  84.857143
std       3.02765   6.121780
min       1.00000  76.000000
25%       3.25000  81.000000
50%       5.50000  85.000000
75%       7.75000  89.500000
max      10.00000  92.000000

In [53]:
df.isnull().sum()

student_id    0
subject       0
score         3
grade         0
dtype: int64

In [50]:
(df.isnull().sum()/len(df)) * 100

student_id     0.0
subject        0.0
score         30.0
grade          0.0
dtype: float64

In [56]:
df.groupby('subject')['score'].median()

subject
Maths      88.0
Science    84.0
Name: score, dtype: float64

In [73]:
df = df.fillna(86)

In [65]:
df.fillna(df.groupby('subject')['score'].median())

   student_id  subject  score grade
0           1    Maths   85.0     A
1           2  Science    NaN     B
2           3    Maths   92.0     A
3           4  Science   78.0     B
4           5    Maths    NaN     A
5           6  Science   88.0     A
6           7    Maths   76.0     B
7           8  Science    NaN     B
8           9    Maths   91.0     A
9          10  Science   84.0     B

In [66]:
df.groupby('subject')['score'].mean()

subject
Maths      86.000000
Science    83.333333
Name: score, dtype: float64

In [76]:
df = df.astype({'grade': 'category'})
df

   student_id  subject  score grade
0           1    Maths   85.0     A
1           2  Science   86.0     B
2           3    Maths   92.0     A
3           4  Science   78.0     B
4           5    Maths   86.0     A
5           6  Science   88.0     A
6           7    Maths   76.0     B
7           8  Science   86.0     B
8           9    Maths   91.0     A
9          10  Science   84.0     B

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  10 non-null     int64
 1   subject     10 non-null     object
 2   score       10 non-null     float64
 3   grade       10 non-null     category
dtypes: category(1), float64(1), int64(1), object(1)
memory usage: 506.0+ bytes