<a href="https://colab.research.google.com/github/HarryAI-6748/ml-project/blob/main/Healthcare_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Defining the healthcare data

In [166]:
hlth_data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

Importing pandas and numpy and then creating data frame for further processing

In [167]:
import pandas as pd
import numpy as np
hlth_df = pd.DataFrame(hlth_data)
hlth_df

    patient_id      age weight  blood_pressure  medication insurance_provider
0          101       25     70           120.0     Aspirin         Blue Cross
1          102       34     65           130.0   Metformin              Aetna
2          103     None     80             NaN  Lisinopril              Cigna
3          104       45   None           140.0        None       UnitedHealth
4          105       29     75           125.0     Aspirin               None
5          106     None   None             NaN   Metformin         Blue Cross
6          107       38     68           135.0  Lisinopril              Aetna
7          108       52     90             NaN     Aspirin              Cigna
8          109       27     72           118.0        None       UnitedHealth
9          110       41     85           145.0   Metformin         Blue Cross
10         111       33     78           128.0  Lisinopril              Aetna
11         112  unknown   None             NaN     Aspirin               None
12         113       48     82           138.0        None       UnitedHealth
13         114       26     69           122.0   Metformin         Blue Cross
14         115       35    N/A             NaN     Aspirin              Aetna
15         101       25     70           120.0     Aspirin         Blue Cross
16         107       38     68           135.0  Lisinopril              Aetna
17         118       31     74           126.0   Metformin              Cigna
18         119     None   None             NaN     Aspirin       UnitedHealth
19         120       44     88           142.0        None               None

Creating a copy of the data frame

In [168]:
hlth_df_original = hlth_df.copy()
hlth_df_original.shape
hlth_df_original.isnull().sum()
hlth_df_original.isnull().sum().sum()
hlth_df_original.duplicated().sum()
hlth_df_original.dtypes
hlth_df_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 17 non-null     object
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB

Inspecting the data using info() method to view column data types and non-null counts

In [169]:
hlth_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 17 non-null     object
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB

Inspecting the data using isnull().sum() method to count missing values per column

In [170]:
hlth_df.isnull().sum()

patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

Calculating the percentage of missing values using: (df.isnull().sum() / len(df)) * 100

In [171]:
(hlth_df.isnull().sum() / len(hlth_df)) * 100

patient_id             0.0
age                   15.0
weight                20.0
blood_pressure        30.0
medication            20.0
insurance_provider    15.0
dtype: float64

Inspecting the data using duplicated().sum() method to count duplicate rows

In [172]:
print(f"The number of duplicate rows is: {hlth_df.duplicated().sum()}")
hlth_df[hlth_df.duplicated()]

The number of duplicate rows is: 2

    patient_id age weight  blood_pressure  medication insurance_provider
15         101  25     70           120.0     Aspirin         Blue Cross
16         107  38     68           135.0  Lisinopril              Aetna

Converting age column (i.e object) to numeric
dup_df['age'] = dup_df['age'].astype(int) will not work as the data has null values, which raises coerce error. To convert this type of data, we need to use "pd.to_numeric(df['age'], errors='coerce')"

In [173]:
hlth_df['age'] = pd.to_numeric(hlth_df['age'], errors = 'coerce')

Checking the data type after conversion

In [174]:
hlth_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 16 non-null     float64
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB

Converting weight column (i.e object) to numeric

In [175]:
hlth_df['weight'] = pd.to_numeric(hlth_df['weight'], errors = 'coerce')

Checking the data type after conversion

In [176]:
hlth_df.dtypes

patient_id              int64
age                   float64
weight                float64
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object

Checking how many NEW missing values were created after conversion

In [177]:
x = hlth_df.isnull().sum().sum() - hlth_df_original.isnull().sum().sum()
print(f"The number of NEW missing values is: {x}")

The number of NEW missing values is: 2

Converting insurance_provider to category type using astype('category')

In [178]:
hlth_df['insurance_provider'] = hlth_df['insurance_provider'] = hlth_df['insurance_provider'].astype('category')

Checking the data type after conversion

In [179]:
hlth_df.dtypes

patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

Handling Missing Values in age column using fillna method

In [180]:
hlth_df['age'] = hlth_df['age'].fillna(hlth_df['age'].median())
hlth_df['age']

0     25.0
1     34.0
2     34.5
3     45.0
4     29.0
5     34.5
6     38.0
7     52.0
8     27.0
9     41.0
10    33.0
11    34.5
12    48.0
13    26.0
14    35.0
15    25.0
16    38.0
17    31.0
18    34.5
19    44.0
Name: age, dtype: float64

Handling Missing Values in weight column using fillna method

In [181]:
hlth_df['weight'] = hlth_df['age'].fillna(hlth_df['weight'].median())
hlth_df['weight']

0     25.0
1     34.0
2     34.5
3     45.0
4     29.0
5     34.5
6     38.0
7     52.0
8     27.0
9     41.0
10    33.0
11    34.5
12    48.0
13    26.0
14    35.0
15    25.0
16    38.0
17    31.0
18    34.5
19    44.0
Name: weight, dtype: float64

Handling Missing Values in blood_pressure column using fillna method

In [182]:
hlth_df['blood_pressure'] = hlth_df['age'].fillna(hlth_df['blood_pressure'].median())
hlth_df['blood_pressure']

0     25.0
1     34.0
2     34.5
3     45.0
4     29.0
5     34.5
6     38.0
7     52.0
8     27.0
9     41.0
10    33.0
11    34.5
12    48.0
13    26.0
14    35.0
15    25.0
16    38.0
17    31.0
18    34.5
19    44.0
Name: blood_pressure, dtype: float64

Handling Missing Values in medication column using fillna method

In [183]:
hlth_df['medication'] = hlth_df['medication'].fillna(hlth_df['medication'].mode()[0])
hlth_df['medication']

0        Aspirin
1      Metformin
2     Lisinopril
3        Aspirin
4        Aspirin
5      Metformin
6     Lisinopril
7        Aspirin
8        Aspirin
9      Metformin
10    Lisinopril
11       Aspirin
12       Aspirin
13     Metformin
14       Aspirin
15       Aspirin
16    Lisinopril
17     Metformin
18       Aspirin
19       Aspirin
Name: medication, dtype: object

In [184]:
hlth_df

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    25.0            25.0     Aspirin         Blue Cross
1          102  34.0    34.0            34.0   Metformin              Aetna
2          103  34.5    34.5            34.5  Lisinopril              Cigna
3          104  45.0    45.0            45.0     Aspirin       UnitedHealth
4          105  29.0    29.0            29.0     Aspirin                NaN
5          106  34.5    34.5            34.5   Metformin         Blue Cross
6          107  38.0    38.0            38.0  Lisinopril              Aetna
7          108  52.0    52.0            52.0     Aspirin              Cigna
8          109  27.0    27.0            27.0     Aspirin       UnitedHealth
9          110  41.0    41.0            41.0   Metformin         Blue Cross
10         111  33.0    33.0            33.0  Lisinopril              Aetna
11         112  34.5    34.5            34.5     Aspirin                NaN
12         113  48.0    48.0            48.0     Aspirin       UnitedHealth
13         114  26.0    26.0            26.0   Metformin         Blue Cross
14         115  35.0    35.0            35.0     Aspirin              Aetna
15         101  25.0    25.0            25.0     Aspirin         Blue Cross
16         107  38.0    38.0            38.0  Lisinopril              Aetna
17         118  31.0    31.0            31.0   Metformin              Cigna
18         119  34.5    34.5            34.5     Aspirin       UnitedHealth
19         120  44.0    44.0            44.0     Aspirin                NaN

Handling Missing Values in insurance_provider column using fillna method

In [185]:
hlth_df['insurance_provider'] = hlth_df['insurance_provider'].cat.add_categories(['Unknown']).fillna('Unknown')
hlth_df['insurance_provider']

0       Blue Cross
1            Aetna
2            Cigna
3     UnitedHealth
4          Unknown
5       Blue Cross
6            Aetna
7            Cigna
8     UnitedHealth
9       Blue Cross
10           Aetna
11         Unknown
12    UnitedHealth
13      Blue Cross
14           Aetna
15      Blue Cross
16           Aetna
17           Cigna
18    UnitedHealth
19         Unknown
Name: insurance_provider, dtype: category
Categories (5, object): ['Aetna', 'Blue Cross', 'Cigna', 'UnitedHealth', 'Unknown']

Verifying number missing values

In [186]:
print(hlth_df.isnull().sum().sum())

0

Handling Duplicates

Getting the duplicate rows using duplicated() method using argument "keep = false" which will mark all the duplicate rows as "True"

In [187]:
hlth_df[hlth_df.duplicated(keep = False)]

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    25.0            25.0     Aspirin         Blue Cross
6          107  38.0    38.0            38.0  Lisinopril              Aetna
15         101  25.0    25.0            25.0     Aspirin         Blue Cross
16         107  38.0    38.0            38.0  Lisinopril              Aetna

Identifying duplicates based on patient_id only using df.duplicated(subset=['patient_id'])

In [188]:
hlth_df[hlth_df.duplicated(subset = ['patient_id'])]

    patient_id   age  weight  blood_pressure  medication insurance_provider
15         101  25.0    25.0            25.0     Aspirin         Blue Cross
16         107  38.0    38.0            38.0  Lisinopril              Aetna

In [189]:
hlth_df.shape

(20, 6)

Removing duplicates keeping first occurrence: df.drop_duplicates(subset=['patient_id'], keep='first')

In [195]:
hlth_df = hlth_df.drop_duplicates(subset = ['patient_id'], keep = 'first')
hlth_df

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    25.0            25.0     Aspirin         Blue Cross
1          102  34.0    34.0            34.0   Metformin              Aetna
2          103  34.5    34.5            34.5  Lisinopril              Cigna
3          104  45.0    45.0            45.0     Aspirin       UnitedHealth
4          105  29.0    29.0            29.0     Aspirin            Unknown
5          106  34.5    34.5            34.5   Metformin         Blue Cross
6          107  38.0    38.0            38.0  Lisinopril              Aetna
7          108  52.0    52.0            52.0     Aspirin              Cigna
8          109  27.0    27.0            27.0     Aspirin       UnitedHealth
9          110  41.0    41.0            41.0   Metformin         Blue Cross
10         111  33.0    33.0            33.0  Lisinopril              Aetna
11         112  34.5    34.5            34.5     Aspirin            Unknown
12         113  48.0    48.0            48.0     Aspirin       UnitedHealth
13         114  26.0    26.0            26.0   Metformin         Blue Cross
14         115  35.0    35.0            35.0     Aspirin              Aetna
17         118  31.0    31.0            31.0   Metformin              Cigna
18         119  34.5    34.5            34.5     Aspirin       UnitedHealth
19         120  44.0    44.0            44.0     Aspirin            Unknown

In [196]:
hlth_df.shape

(18, 6)

Complete Workflow with Verification

In [197]:
print("\t\t\t\t\tGenerating a verification report", "\n\n")
print(f"1. The shape of the original data was: {hlth_df_original.shape} and the shape of processed data is: {hlth_df.shape}", "\n")
print(f"2. The number of missing values in the original data was: {hlth_df_original.isnull().sum().sum()} and the number of missing values in the processed data is: {hlth_df.isnull().sum().sum()}", "\n")
print(f"3. The number of duplicates in the original data were: {hlth_df_original.duplicated().sum()} and the number of duplicates in the procesed data is: {hlth_df.duplicated().sum()}", "\n")
print(f"4. The data types before the processing was: \n\n{hlth_df_original.dtypes}\n\n")
print(f"5. The data types after the processing is: \n\n{hlth_df.dtypes}\n\n")

					Generating a verification report


1. The shape of the original data was: (20, 6) and the shape of processed data is: (18, 6)

2. The number of missing values in the original data was: 20 and the number of missing values in the processed data is: 0

3. The number of duplicates in the original data were: 2 and the number of duplicates in the procesed data is: 0

4. The data types before the processing was:

patient_id              int64
age                    object
weight                 object
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object


5. The data types after the processing is:

patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object