<a href="https://colab.research.google.com/github/HarryAI-6748/ml-project/blob/main/Public_Rest_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Send a GET request to the endpoint using the requests library inside a try-except block. Print the HTTP status code. If the request is successful (status code 200), print the total number of countries retrieved. If it fails, print a descriptive error message.

In [70]:
import requests
import json
import pandas as pd

In [81]:
def countries_data():
  """Countries data from restcountries.com"""
  url = "https://restcountries.com/v3.1/all"
  params = {"fields":"name,population,region,area"}

  try:
    response = requests.get(url, params, timeout=10)
    print(f"HTTP status code: {response.status_code}")
    if response.status_code == 200:
      print(f"Total number of countries retrieved: {len(response.json())}")

  except requests.exceptions.Timeout:
    print("Request timed out — server did not respond in 10 seconds.")
    return None
  except requests.exceptions.ConnectionError:
    print("Connection failed — check your internet connection.")
    return None
  except:
    print("An unexpected error occurred. Pls try again and search the detailed explaination on AI")
    return None

In [83]:
countries_data()

HTTP status code: 200
Total number of countries retrieved: 250

Parse the JSON response and extract the following fields for each country: common_name, population, region, and area. Store the results in a Pandas DataFrame and display the first 10 rows.

In [109]:
url = "https://restcountries.com/v3.1/all"
params = {"fields":"name,population,region,area"}
response = requests.get(url, params)
count_data = response.json()
df = pd.DataFrame(count_data)
df['common_name'] = df['name'].apply(lambda x: x['common'])
df.drop(columns = ['name'], inplace = True)
df = df[['common_name', 'population', 'region', 'area']]
df.head(10)

             common_name  population    region       area
0            Ivory Coast    31719275    Africa   322463.0
1                  Italy    58927633    Europe   301336.0
2             Kyrgyzstan     7281800      Asia   199951.0
3       Papua New Guinea    11781559   Oceania   462840.0
4                   Fiji      900869   Oceania    18272.0
5   United Arab Emirates    11294243      Asia    83600.0
6  Saint Kitts and Nevis       51320  Americas      261.0
7          French Guiana      292354  Americas    83534.0
8               Tanzania    68153004    Africa   947303.0
9                 Angola    36170961    Africa  1246700.0

Which region has the highest total population?

In [148]:
dm = df.groupby('region')['population'].sum()
dm = dm.reset_index()
dm[dm['population'].max() == dm['population']]['region']

3    Asia
Name: region, dtype: object

In [149]:
max_pupulation = df.groupby('region')['population'].sum().sort_values(ascending=False).reset_index()['region'][0]
print(f"The region with maximum population is {max_pupulation}.")

The region with maximum population is Asia.

Which country has the largest area?

In [165]:
max_area = df.groupby('common_name')['area'].sum().sort_values(ascending=False).reset_index()['common_name'][0]
print(f"The country with maximum area is {max_area}.")

The country with maximum area is Russia.

In [164]:
max_area = df['area'].max()

df[df['area'] == max_area]['common_name']
print(f"The country with maximum area is {max_area}.")

The country with maximum area is 17098246.0.

In [106]:
cols = ['common_name'] + [col for col in df.columns if col != 'common_name']
df = df[cols]
display(df.head(10))

             common_name    region       area  population
0            Ivory Coast    Africa   322463.0    31719275
1                  Italy    Europe   301336.0    58927633
2             Kyrgyzstan      Asia   199951.0     7281800
3       Papua New Guinea   Oceania   462840.0    11781559
4                   Fiji   Oceania    18272.0      900869
5   United Arab Emirates      Asia    83600.0    11294243
6  Saint Kitts and Nevis  Americas      261.0       51320
7          French Guiana  Americas    83534.0      292354
8               Tanzania    Africa   947303.0    68153004
9                 Angola    Africa  1246700.0    36170961

In [107]:
# Define the new order of columns manually
new_column_order = ['common_name', 'population', 'region', 'area']

# Reindex the DataFrame with the new column order
df_reordered = df[new_column_order]

display(df_reordered.head(10))

             common_name  population    region       area
0            Ivory Coast    31719275    Africa   322463.0
1                  Italy    58927633    Europe   301336.0
2             Kyrgyzstan     7281800      Asia   199951.0
3       Papua New Guinea    11781559   Oceania   462840.0
4                   Fiji      900869   Oceania    18272.0
5   United Arab Emirates    11294243      Asia    83600.0
6  Saint Kitts and Nevis       51320  Americas      261.0
7          French Guiana      292354  Americas    83534.0
8               Tanzania    68153004    Africa   947303.0
9                 Angola    36170961    Africa  1246700.0

In [90]:
df['common_name'] = df['name'].apply(lambda x: x['common'])
display(df.head(10))

,name,region,area,population,common_name
0,"{'common': 'Ivory Coast', 'official': 'Republi...",Africa,322463.0,31719275,Ivory Coast
1,"{'common': 'Italy', 'official': 'Italian Repub...",Europe,301336.0,58927633,Italy
2,"{'common': 'Kyrgyzstan', 'official': 'Kyrgyz R...",Asia,199951.0,7281800,Kyrgyzstan
3,"{'common': 'Papua New Guinea', 'official': 'In...",Oceania,462840.0,11781559,Papua New Guinea
4,"{'common': 'Fiji', 'official': 'Republic of Fi...",Oceania,18272.0,900869,Fiji
5,"{'common': 'United Arab Emirates', 'official':...",Asia,83600.0,11294243,United Arab Emirates
6,"{'common': 'Saint Kitts and Nevis', 'official'...",Americas,261.0,51320,Saint Kitts and Nevis
7,"{'common': 'French Guiana', 'official': 'Guian...",Americas,83534.0,292354,French Guiana
8,"{'common': 'Tanzania', 'official': 'United Rep...",Africa,947303.0,68153004,Tanzania
9,"{'common': 'Angola', 'official': 'Republic of ...",Africa,1246700.0,36170961,Angola

In [91]:
df = df.drop(columns=['name'])
display(df.head(10))

     region       area  population            common_name
0    Africa   322463.0    31719275            Ivory Coast
1    Europe   301336.0    58927633                  Italy
2      Asia   199951.0     7281800             Kyrgyzstan
3   Oceania   462840.0    11781559       Papua New Guinea
4   Oceania    18272.0      900869                   Fiji
5      Asia    83600.0    11294243   United Arab Emirates
6  Americas      261.0       51320  Saint Kitts and Nevis
7  Americas    83534.0      292354          French Guiana
8    Africa   947303.0    68153004               Tanzania
9    Africa  1246700.0    36170961                 Angola

In [64]:
countries_data()

HTTP status code: 200
Total number of countries retrieved: 250

[{'name': {'common': 'Cook Islands',
   'official': 'Cook Islands',
   'nativeName': {'eng': {'official': 'Cook Islands',
     'common': 'Cook Islands'},
    'rar': {'official': "Kūki 'Āirani", 'common': "Kūki 'Āirani"}}},
  'region': 'Oceania',
  'area': 236.0,
  'population': 15040},
 {'name': {'common': 'Guinea',
   'official': 'Republic of Guinea',
   'nativeName': {'fra': {'official': 'République de Guinée',
     'common': 'Guinée'}}},
  'region': 'Africa',
  'area': 245857.0,
  'population': 14363931},
 {'name': {'common': 'Christmas Island',
   'official': 'Territory of Christmas Island',
   'nativeName': {'eng': {'official': 'Territory of Christmas Island',
     'common': 'Christmas Island'}}},
  'region': 'Oceania',
  'area': 135.0,
  'population': 1692},
 {'name': {'common': 'Togo',
   'official': 'Togolese Republic',
   'nativeName': {'fra': {'official': 'République togolaise',
     'common': 'Togo'}}},
  'region': 'Africa',
  'area': 56785.0,
  'population': 8095498},
 {'name': {'common': 'Taiwan',
   'official': 'Republic of China (Taiwan)',
   'nativeName': {'zho': {'official': '中華民國', 'common': '台灣'}}},
  'region': 'Asia',
  'area': 36197.0,
  'population': 23317031},
 {'name': {'common': 'Kyrgyzstan',
   'official': 'Kyrgyz Republic',
   'nativeName': {'kir': {'official': 'Кыргыз Республикасы',
     'common': 'Кыргызстан'},
    'rus': {'official': 'Кыргызская Республика', 'common': 'Киргизия'}}},
  'region': 'Asia',
  'area': 199951.0,
  'population': 7281800},
 {'name': {'common': 'Suriname',
   'official': 'Republic of Suriname',
   'nativeName': {'nld': {'official': 'Republiek Suriname',
     'common': 'Suriname'}}},
  'region': 'Americas',
  'area': 163820.0,
  'population': 616500},
 {'name': {'common': 'Dominican Republic',
   'official': 'Dominican Republic',
   'nativeName': {'spa': {'official': 'República Dominicana',
     'common': 'República Dominicana'}}},
  'region': 'Americas',
  'area': 48671.0,
  'population': 10771504},
 {'name': {'common': 'Guatemala',
   'official': 'Republic of Guatemala',
   'nativeName': {'spa': {'official': 'República de Guatemala',
     'common': 'Guatemala'}}},
  'region': 'Americas',
  'area': 108889.0,
  'population': 18079810},
 {'name': {'common': 'Algeria',
   'official': "People's Democratic Republic of Algeria",
   'nativeName': {'ara': {'official': 'الجمهورية الديمقراطية الشعبية الجزائرية',
     'common': 'الجزائر'}}},
  'region': 'Africa',
  'area': 2381741.0,
  'population': 47400000},
 {'name': {'common': 'Ukraine',
   'official': 'Ukraine',
   'nativeName': {'ukr': {'official': 'Україна', 'common': 'Україна'}}},
  'region': 'Europe',
  'area': 603550.0,
  'population': 32862000},
 {'name': {'common': 'Saint Kitts and Nevis',
   'official': 'Federation of Saint Christopher and Nevis',
   'nativeName': {'eng': {'official': 'Federation of Saint Christopher and Nevis',
     'common': 'Saint Kitts and Nevis'}}},
  'region': 'Americas',
  'area': 261.0,
  'population': 51320},
 {'name': {'common': 'Croatia',
   'official': 'Republic of Croatia',
   'nativeName': {'hrv': {'official': 'Republika Hrvatska',
     'common': 'Hrvatska'}}},
  'region': 'Europe',
  'area': 56594.0,
  'population': 3866233},
 {'name': {'common': 'Equatorial Guinea',
   'official': 'Republic of Equatorial Guinea',
   'nativeName': {'fra': {'official': 'République de la Guinée Équatoriale',
     'common': 'Guinée équatoriale'},
    'por': {'official': 'República da Guiné Equatorial',
     'common': 'Guiné Equatorial'},
    'spa': {'official': 'República de Guinea Ecuatorial',
     'common': 'Guinea Ecuatorial'}}},
  'region': 'Africa',
  'area': 28051.0,
  'population': 1668768},
 {'name': {'common': 'Panama',
   'official': 'Republic of Panama',
   'nativeName': {'spa': {'official': 'República de Panamá',
     'common': 'Panamá'}}},
  'region': 'Americas',
  'area': 75417.0,
  'population': 4064780},
 {'name': {'common': 'Belgium',
   'official': 'Kingdom of Belgium',
   'nativeName': {'deu': {'official': 'Königreich Belgien',
     'common': 'Belgien'},
    'fra': {'official': 'Royaume de Belgique', 'common': 'Belgique'},
    'nld': {'official': 'Koninkrijk België', 'common': 'België'}}},
  'region': 'Europe',
  'area': 30528.0,
  'population': 11825551},
 {'name': {'common': 'Bouvet Island',
   'official': 'Bouvet Island',
   'nativeName': {'nor': {'official': 'Bouvetøya', 'common': 'Bouvetøya'}}},
  'region': 'Antarctic',
  'area': 49.0,
  'population': 0},
 {'name': {'common': 'Rwanda',
   'official': 'Republic of Rwanda',
   'nativeName': {'eng': {'official': 'Republic of Rwanda',
     'common': 'Rwanda'},
    'fra': {'official': 'République rwandaise', 'common': 'Rwanda'},
    'kin': {'official': "Repubulika y'u Rwanda", 'common': 'Rwanda'}}},
  'region': 'Africa',
  'area': 26338.0,
  'population': 14104969},
 {'name': {'common': 'French Southern and Antarctic Lands',
   'official': 'Territory of the French Southern and Antarctic Lands',
   'nativeName': {'fra': {'official': 'Territoire des Terres australes et antarctiques françaises',
     'common': 'Terres australes et antarctiques françaises'}}},
  'region': 'Antarctic',
  'area': 7747.0,
  'population': 400},
 {'name': {'common': 'Cape Verde',
   'official': 'Republic of Cabo Verde',
   'nativeName': {'por': {'official': 'República de Cabo Verde',
     'common': 'Cabo Verde'}}},
  'region': 'Africa',
  'area': 4033.0,
  'population': 491233},
 {'name': {'common': 'South Korea',
   'official': 'Republic of Korea',
   'nativeName': {'kor': {'official': '대한민국', 'common': '한국'}}},
  'region': 'Asia',
  'area': 100210.0,
  'population': 51159889},
 {'name': {'common': 'Guam',
   'official': 'Guam',
   'nativeName': {'cha': {'official': 'Guåhån', 'common': 'Guåhån'},
    'eng': {'official': 'Guam', 'common': 'Guam'},
    'spa': {'official': 'Guam', 'common': 'Guam'}}},
  'region': 'Oceania',
  'area': 549.0,
  'population': 153836},
 {'name': {'common': 'Andorra',
   'official': 'Principality of Andorra',
   'nativeName': {'cat': {'official': "Principat d'Andorra",
     'common': 'Andorra'}}},
  'region': 'Europe',
  'area': 468.0,
  'population': 88406},
 {'name': {'common': 'Senegal',
   'official': 'Republic of Senegal',
   'nativeName': {'fra': {'official': 'République du Sénégal',
     'common': 'Sénégal'}}},
  'region': 'Africa',
  'area': 196722.0,
  'population': 18593258},
 {'name': {'common': 'Uruguay',
   'official': 'Oriental Republic of Uruguay',
   'nativeName': {'spa': {'official': 'República Oriental del Uruguay',
     'common': 'Uruguay'}}},
  'region': 'Americas',
  'area': 181034.0,
  'population': 3499451},
 {'name': {'common': 'Republic of the Congo',
   'official': 'Republic of the Congo',
   'nativeName': {'fra': {'official': 'République du Congo',
     'common': 'République du Congo'},
    'kon': {'official': 'Repubilika ya Kongo',
     'common': 'Repubilika ya Kongo'},
    'lin': {'official': 'Republíki ya Kongó',
     'common': 'Republíki ya Kongó'}}},
  'region': 'Africa',
  'area': 342000.0,
  'population': 6142180},
 {'name': {'common': 'Namibia',
   'official': 'Republic of Namibia',
   'nativeName': {'afr': {'official': 'Republiek van Namibië',
     'common': 'Namibië'},
    'deu': {'official': 'Republik Namibia', 'common': 'Namibia'},
    'eng': {'official': 'Republic of Namibia', 'common': 'Namibia'},
    'her': {'official': 'Republic of Namibia', 'common': 'Namibia'},
    'hgm': {'official': 'Republic of Namibia', 'common': 'Namibia'},
    'kwn': {'official': 'Republic of Namibia', 'common': 'Namibia'},
    'loz': {'official': 'Republic of Namibia', 'common': 'Namibia'},
    'ndo': {'official': 'Republic of Namibia', 'common': 'Namibia'},
    'tsn': {'official': 'Lefatshe la Namibia', 'common': 'Namibia'}}},
  'region': 'Africa',
  'area': 825615.0,
  'population': 3022401},
 {'name': {'common': 'Singapore',
   'official': 'Republic of Singapore',
   'nativeName': {'eng': {'official': 'Republic of Singapore',
     'common': 'Singapore'},
    'zho': {'official': '新加坡共和国', 'common': '新加坡'},
    'msa': {'official': 'Republik Singapura', 'common': 'Singapura'},
    'tam': {'official': 'சிங்கப்பூர் குடியரசு', 'common': 'சிங்கப்பூர்'}}},
  'region': 'Asia',
  'area': 710.0,
  'population': 6110200},
 {'name': {'common': 'Finland',
   'official': 'Republic of Finland',
   'nativeName': {'fin': {'official': 'Suomen tasavalta', 'common': 'Suomi'},
    'swe': {'official': 'Republiken Finland', 'common': 'Finland'}}},
  'region': 'Europe',
  'area': 338455.0,
  'population': 5650325},
 {'name': {'common': 'Egypt',
   'official': 'Arab Republic of Egypt',
   'nativeName': {'ara': {'official': 'جمهورية مصر العربية',
     'common': 'مصر'}}},
  'region': 'Africa',
  'area': 1002450.0,
  'population': 107271260},
 {'name': {'common': 'Palau',
   'official': 'Republic of Palau',
   'nativeName': {'eng': {'official': 'Republic of Palau', 'common': 'Palau'},
    'pau': {'official': 'Beluu er a Belau', 'common': 'Belau'}}},
  'region': 'Oceania',
  'area': 459.0,
  'population': 16733},
 {'name': {'common': 'American Samoa',
   'official': 'American Samoa',
   'nativeName': {'eng': {'official': 'American Samoa',
     'common': 'American Samoa'},
    'smo': {'official': 'Sāmoa Amelika', 'common': 'Sāmoa Amelika'}}},
  'region': 'Oceania',
  'area': 199.0,
  'population': 49710},
 {'name': {'common': 'Antigua and Barbuda',
   'official': 'Antigua and Barbuda',
   'nativeName': {'eng': {'official': 'Antigua and Barbuda',
     'common': 'Antigua and Barbuda'}}},
  'region': 'Americas',
  'area': 442.0,
  'population': 103603},
 {'name': {'common': 'Seychelles',
   'official': 'Republic of Seychelles',
   'nativeName': {'crs': {'official': 'Repiblik Sesel', 'common': 'Sesel'},
    'eng': {'official': 'Republic of Seychelles', 'common': 'Seychelles'},
    'fra': {'official': 'République des Seychelles', 'common': 'Seychelles'}}},
  'region': 'Africa',
  'area': 452.0,
  'population': 122729},
 {'name': {'common': 'Kuwait',
   'official': 'State of Kuwait',
   'nativeName': {'ara': {'official': 'دولة الكويت', 'common': 'الكويت'}}},
  'region': 'Asia',
  'area': 17818.0,
  'population': 4881254},
 {'name': {'common': 'Greece',
   'official': 'Hellenic Republic',
   'nativeName': {'ell': {'official': 'Ελληνική Δημοκρατία',
     'common': 'Ελλάδα'}}},
  'region': 'Europe',
  'area': 131990.0,
  'population': 10400720},
 {'name': {'common': 'Kiribati',
   'official': 'Independent and Sovereign Republic of Kiribati',
   'nativeName': {'eng': {'official': 'Independent and Sovereign Republic of Kiribati',
     'common': 'Kiribati'},
    'gil': {'official': 'Ribaberiki Kiribati', 'common': 'Kiribati'}}},
  'region': 'Oceania',
  'area': 811.0,
  'population': 120740},
 {'name': {'common': 'Cyprus',
   'official': 'Republic of Cyprus',
   'nativeName': {'ell': {'official': 'Δημοκρατία της Κύπρος',
     'common': 'Κύπρος'},
    'tur': {'official': 'Kıbrıs Cumhuriyeti', 'common': 'Kıbrıs'}}},
  'region': 'Europe',
  'area': 9251.0,
  'population': 1442614},
 {'name': {'common': 'Mali',
   'official': 'Republic of Mali',
   'nativeName': {'fra': {'official': 'République du Mali',
     'common': 'Mali'}}},
  'region': 'Africa',
  'area': 1240192.0,
  'population': 22395489},
 {'name': {'common': 'Bermuda',
   'official': 'Bermuda',
   'nativeName': {'eng': {'official': 'Bermuda', 'common': 'Bermuda'}}},
  'region': 'Americas',
  'area': 54.0,
  'population': 64055},
 {'name': {'common': 'Greenland',
   'official': 'Greenland',
   'nativeName': {'kal': {'official': 'Kalaallit Nunaat',
     'common': 'Kalaallit Nunaat'}}},
  'region': 'Americas',
  'area': 2166086.0,
  'population': 56542},
 {'name': {'common': 'Eritrea',
   'official': 'State of Eritrea',
   'nativeName': {'ara': {'official': 'دولة إرتريا', 'common': 'إرتريا\u200e'},
    'eng': {'official': 'State of Eritrea', 'common': 'Eritrea'},
    'tir': {'official': 'ሃገረ ኤርትራ', 'common': 'ኤርትራ'}}},
  'region': 'Africa',
  'area': 117600.0,
  'population': 3607000},
 {'name': {'common': 'Tanzania',
   'official': 'United Republic of Tanzania',
   'nativeName': {'eng': {'official': 'United Republic of Tanzania',
     'common': 'Tanzania'},
    'swa': {'official': 'Jamhuri ya Muungano wa Tanzania',
     'common': 'Tanzania'}}},
  'region': 'Africa',
  'area': 947303.0,
  'population': 68153004},
 {'name': {'common': 'Vietnam',
   'official': 'Socialist Republic of Vietnam',
   'nativeName': {'vie': {'official': 'Cộng hòa xã hội chủ nghĩa Việt Nam',
     'common': 'Việt Nam'}}},
  'region': 'Asia',
  'area': 331212.0,
  'population': 101343800},
 {'name': {'common': 'Chad',
   'official': 'Republic of Chad',
   'nativeName': {'ara': {'official': 'جمهورية تشاد', 'common': 'تشاد\u200e'},
    'fra': {'official': 'République du Tchad', 'common': 'Tchad'}}},
  'region': 'Africa',
  'area': 1284000.0,
  'population': 19340757},
 {'name': {'common': 'Ivory Coast',
   'official': "Republic of Côte d'Ivoire",
   'nativeName': {'fra': {'official': "République de Côte d'Ivoire",
     'common': "Côte d'Ivoire"}}},
  'region': 'Africa',
  'area': 322463.0,
  'population': 31719275},
 {'name': {'common': 'Georgia',
   'official': 'Georgia',
   'nativeName': {'kat': {'official': 'საქართველო', 'common': 'საქართველო'}}},
  'region': 'Asia',
  'area': 69700.0,
  'population': 4000921},
 {'name': {'common': 'Isle of Man',
   'official': 'Isle of Man',
   'nativeName': {'eng': {'official': 'Isle of Man', 'common': 'Isle of Man'},
    'glv': {'official': 'Ellan Vannin or Mannin', 'common': 'Mannin'}}},
  'region': 'Europe',
  'area': 572.0,
  'population': 84530},
 {'name': {'common': 'South Georgia',
   'official': 'South Georgia and the South Sandwich Islands',
   'nativeName': {'eng': {'official': 'South Georgia and the South Sandwich Islands',
     'common': 'South Georgia'}}},
  'region': 'Antarctic',
  'area': 3903.0,
  'population': 0},
 {'name': {'common': 'Bolivia',
   'official': 'Plurinational State of Bolivia',
   'nativeName': {'aym': {'official': 'Wuliwya Suyu', 'common': 'Wuliwya'},
    'grn': {'official': 'Tetã Volívia', 'common': 'Volívia'},
    'que': {'official': 'Buliwya Mamallaqta', 'common': 'Buliwya'},
    'spa': {'official': 'Estado Plurinacional de Bolivia',
     'common': 'Bolivia'}}},
  'region': 'Americas',
  'area': 1098581.0,
  'population': 11365333},
 {'name': {'common': 'United States Minor Outlying Islands',
   'official': 'United States Minor Outlying Islands',
   'nativeName': {'eng': {'official': 'United States Minor Outlying Islands',
     'common': 'United States Minor Outlying Islands'}}},
  'region': 'Americas',
  'area': 34.2,
  'population': 0},
 {'name': {'common': 'Denmark',
   'official': 'Kingdom of Denmark',
   'nativeName': {'dan': {'official': 'Kongeriget Danmark',
     'common': 'Danmark'}}},
  'region': 'Europe',
  'area': 43094.0,
  'population': 6011488},
 {'name': {'common': 'Turkmenistan',
   'official': 'Turkmenistan',
   'nativeName': {'rus': {'official': 'Туркменистан', 'common': 'Туркмения'},
    'tuk': {'official': 'Türkmenistan', 'common': 'Türkmenistan'}}},
  'region': 'Asia',
  'area': 488100.0,
  'population': 7057841},
 {'name': {'common': 'Niger',
   'official': 'Republic of Niger',
   'nativeName': {'fra': {'official': 'République du Niger',
     'common': 'Niger'}}},
  'region': 'Africa',
  'area': 1267000.0,
  'population': 26312034},
 {'name': {'common': 'Micronesia',
   'official': 'Federated States of Micronesia',
   'nativeName': {'eng': {'official': 'Federated States of Micronesia',
     'common': 'Micronesia'}}},
  'region': 'Oceania',
  'area': 702.0,
  'population': 105564},
 {'name': {'common': 'Jersey',
   'official': 'Bailiwick of Jersey',
   'nativeName': {'eng': {'official': 'Bailiwick of Jersey',
     'common': 'Jersey'},
    'fra': {'official': 'Bailliage de Jersey', 'common': 'Jersey'},
    'nrf': {'official': 'Bailliage dé Jèrri', 'common': 'Jèrri'}}},
  'region': 'Europe',
  'area': 116.0,
  'population': 103267},
 {'name': {'common': 'Cayman Islands',
   'official': 'Cayman Islands',
   'nativeName': {'eng': {'official': 'Cayman Islands',
     'common': 'Cayman Islands'}}},
  'region': 'Americas',
  'area': 264.0,
  'population': 84738},
 {'name': {'common': 'Liechtenstein',
   'official': 'Principality of Liechtenstein',
   'nativeName': {'deu': {'official': 'Fürstentum Liechtenstein',
     'common': 'Liechtenstein'}}},
  'region': 'Europe',
  'area': 160.0,
  'population': 40900},
 {'name': {'common': 'Bosnia and Herzegovina',
   'official': 'Bosnia and Herzegovina',
   'nativeName': {'bos': {'official': 'Bosna i Hercegovina',
     'common': 'Bosna i Hercegovina'},
    'hrv': {'official': 'Bosna i Hercegovina',
     'common': 'Bosna i Hercegovina'},
    'srp': {'official': 'Босна и Херцеговина',
     'common': 'Босна и Херцеговина'}}},
  'region': 'Europe',
  'area': 51209.0,
  'population': 3422000},
 {'name': {'common': 'France',
   'official': 'French Republic',
   'nativeName': {'fra': {'official': 'République française',
     'common': 'France'}}},
  'region': 'Europe',
  'area': 543908.0,
  'population': 66351959},
 {'name': {'common': 'French Polynesia',
   'official': 'French Polynesia',
   'nativeName': {'fra': {'official': 'Polynésie française',
     'common': 'Polynésie française'}}},
  'region': 'Oceania',
  'area': 4167.0,
  'population': 279500},
 {'name': {'common': 'Kazakhstan',
   'official': 'Republic of Kazakhstan',
   'nativeName': {'kaz': {'official': 'Қазақстан Республикасы',
     'common': 'Қазақстан'},
    'rus': {'official': 'Республика Казахстан', 'common': 'Казахстан'}}},
  'region': 'Asia',
  'area': 2724900.0,
  'population': 20426568},
 {'name': {'common': 'Angola',
   'official': 'Republic of Angola',
   'nativeName': {'por': {'official': 'República de Angola',
     'common': 'Angola'}}},
  'region': 'Africa',
  'area': 1246700.0,
  'population': 36170961},
 {'name': {'common': 'New Zealand',
   'official': 'New Zealand',
   'nativeName': {'eng': {'official': 'New Zealand', 'common': 'New Zealand'},
    'mri': {'official': 'Aotearoa', 'common': 'Aotearoa'},
    'nzs': {'official': 'New Zealand', 'common': 'New Zealand'}}},
  'region': 'Oceania',
  'area': 268838.0,
  'population': 5324700},
 {'name': {'common': 'Puerto Rico',
   'official': 'Commonwealth of Puerto Rico',
   'nativeName': {'eng': {'official': 'Commonwealth of Puerto Rico',
     'common': 'Puerto Rico'},
    'spa': {'official': 'Estado Libre Asociado de Puerto Rico',
     'common': 'Puerto Rico'}}},
  'region': 'Americas',
  'area': 8870.0,
  'population': 3203295},
 {'name': {'common': 'Saudi Arabia',
   'official': 'Kingdom of Saudi Arabia',
   'nativeName': {'ara': {'official': 'المملكة العربية السعودية',
     'common': 'العربية السعودية'}}},
  'region': 'Asia',
  'area': 2149690.0,
  'population': 35300280},
 {'name': {'common': 'Montenegro',
   'official': 'Montenegro',
   'nativeName': {'cnr': {'official': 'Црна Гора', 'common': 'Црна Гора'}}},
  'region': 'Europe',
  'area': 13812.0,
  'population': 623327},
 {'name': {'common': 'South Africa',
   'official': 'Republic of South Africa',
   'nativeName': {'afr': {'official': 'Republiek van Suid-Afrika',
     'common': 'South Africa'},
    'eng': {'official': 'Republic of South Africa', 'common': 'South Africa'},
    'nbl': {'official': 'IRiphabliki yeSewula Afrika',
     'common': 'Sewula Afrika'},
    'nso': {'official': 'Rephaboliki ya Afrika-Borwa ',
     'common': 'Afrika-Borwa'},
    'sot': {'official': 'Rephaboliki ya Afrika Borwa',
     'common': 'Afrika Borwa'},
    'ssw': {'official': 'IRiphabhulikhi yeNingizimu Afrika',
     'common': 'Ningizimu Afrika'},
    'tsn': {'official': 'Rephaboliki ya Aforika Borwa',
     'common': 'Aforika Borwa'},
    'tso': {'official': 'Riphabliki ra Afrika Dzonga',
     'common': 'Afrika Dzonga'},
    'ven': {'official': 'Riphabuḽiki ya Afurika Tshipembe',
     'common': 'Afurika Tshipembe'},

In [55]:
x = {'name': {'common': 'Burkina Faso',
   'official': 'Burkina Faso',
   'nativeName': {'fra': {'official': 'République du Burkina',
     'common': 'Burkina Faso'}}}
}

In [58]:
x['name']['common']

'Burkina Faso'